---
title: "dataanalytics_assignment8"
format: html
editor: visual
---

# Assignment 8

## Preliminaries

```{r}
library(tidyverse)
library(skimr)
library(ggplot2)
library(generics)
library(dplyr)
library(broom)
```

## Step 1

```{r}
#Loading in dataset as a tibble named 'd'
f <- "https://raw.githubusercontent.com/difiore/ada-datasets/main/Street_et_al_2017.csv"
d <- read_csv(f, col_names = TRUE)

#Exploratory data analysis
skim(d)
```

## Step 2

```{r}
#From this dataset, plot brain size (ECV) as a function of... 

#social group size (Group_size)
plot(data = d, log(ECV) ~ log(Group_size))

#longevity (Longevity)
plot(data = d, log(ECV) ~ log(Longevity))

#juvenile period length (Weaning)
plot(data = d, log(ECV) ~ log(Weaning))

#reproductive lifespan (Repro_lifespan).
plot(data = d, log(ECV) ~ log(Repro_lifespan))
```

## Step 3

```{r}
#Derive by hand the ordinary least squares regression coefficients B1 and B0 for ECV as a function of social group size.
#Simplifying variables
y <- d$ECV
x <- d$Group_size
#Calculating Beta1 (slope) by hand
(b1_hand <- cor(x, y,  use = "complete.obs") * (sd(y, na.rm = TRUE)/sd(x, na.rm = TRUE)))
#Calculating Beta0 (y-int) by hand
(b0_hand <- mean(y, na.rm = TRUE) - b1_hand * mean(x, na.rm = TRUE))

```

## Step 4

```{r}
#Confirm that you get the same results using the lm() function.
(lm(formula = ECV ~ Group_size, data = d, na.rm = TRUE))
m <- lm(ECV ~ Group_size, d, na.rm = TRUE)
```

## Step 5

```{r}
#Repeat the analysis above for three different major radiations of primates - 

#“catarrhines”
 #filter for group
  cat <- filter(d, Taxonomic_group == "Catarrhini")
  head(cat)
 #making my x,y
  y_cat <- cat$ECV
  x_cat <- cat$Group_size
  
#Finding beta1  
beta1cat <- cor(x_cat, y_cat,  use = "complete.obs") * (sd(y_cat, na.rm = TRUE)/sd(x_cat, na.rm = TRUE))
#Finding beta0
beta0cat <- mean(y_cat, na.rm = TRUE) - beta1cat * mean(x_cat, na.rm = TRUE)
#Confirm with lm() function
(lm(formula = ECV ~ Group_size, data = cat, na.rm = TRUE))

#“platyrrhines” 
  #filter for group
  plat <- filter(d, Taxonomic_group == "Platyrrhini")
  head(plat)
 #making my x,y
  y_plat <- plat$ECV
  x_plat <- plat$Group_size
  
#Finding beta1  
beta1plat <- cor(x_plat, y_plat,  use = "complete.obs") * (sd(y_plat, na.rm = TRUE)/sd(x_plat, na.rm = TRUE))
#Finding beta0
beta0plat <- mean(y_plat, na.rm = TRUE) - beta1plat * mean(x_plat, na.rm = TRUE)
#Confirm with lm() function
(lm(formula = ECV ~ Group_size, data = plat, na.rm = TRUE))  
  
#“strepsirhines” 
  #filter for group
  strep <- filter(d, Taxonomic_group == "Strepsirhini")
  head(strep)
 #making my x,y
  y_strep <- strep$ECV
  x_strep <- strep$Group_size

#Finding beta1  
beta1strep <- cor(x_strep, y_strep,  use = "complete.obs") * (sd(y_strep, na.rm = TRUE)/sd(x_strep, na.rm = TRUE))
#Finding beta0
beta0strep <- mean(y_strep, na.rm = TRUE) - beta1strep * mean(x_strep, na.rm = TRUE)
#Confirm with lm() function
(lm(formula = ECV ~ Group_size, data = strep, na.rm = TRUE))  

```

## Step 6

```{r}
#I am not going to lie, I feel somewhat decent on the rest of this assignment but am very lost here
#For your first regression of ECV on social group size, calculate the standard error for the slope coefficient, 

n <- length(x)
y1 <- b0_hand + b1_hand * x
residuals <- y - y1
sigma2 <- sum(residuals^2) / (n - 2)

#Calculating SE of slope, this is where I botch it, I thibk its because I did not filter the x data properly to remove the blanks :(
SE_b1 <- sqrt(sigma2 / sum((x - (mean(x)))^2))
SE_b1

#the 95% CI, 
ci <- quantile(d, c(0.025, 0.975))
t_crit <- qt(0.975, df = n - 2)
ci <- b1_hand + c(-1, 1) * t_crit * SE_b1

#and the p value associated with this coefficient
t_stat <- b1_hand / SE_b1
p_val <- 2 * (1 - pt(abs(t_stat), df = n - 2)) 

#Also extract this same information from the results of running the lm() function
fit_lm <- lm(ECV ~ Group_size, data = d,na.rm = TRUE)
summary(fit_lm)

```

## Step 7

```{r}
#Use a permutation approach with 1000 permutations to generate a null sampling distribution for the slope coefficient. 

#Prelims
nperm <- 1000 #Setting reps
perm_coefs <- numeric(nperm) #Opening a place to put permutation coeffs into

#Running my permutation
for (i in seq_len(nperm)) {
  d_perm <- d
  d_perm$ECV <- sample(d$ECV)
  perm_coefs[i] <- lm(Group_size ~ ECV, data = d_perm) %>%
    tidy() %>%
    filter(term == "ECV") %>%
    pull(estimate)
}
#Checking histogram
hist(perm_coefs) #Welp she's a bit crooked but still somewhat normal???
```

## Step 8

```{r}
#Use bootstrapping to generate a 95% CI for your estimate of the slope coefficient using both the quantile method and the theory-based method

#Bootstrap confidence interval
nboot <- 1000
boot_coefs <- vector(length = nboot)

for(i in 1:nboot) {
  d_boot <- d[sample(nrow(d), replace = TRUE), ]
  boot_coefs[[i]] <- lm(ECV ~ Group_size, data = d_boot) %>%
    tidy() %>%
    filter(term == "Group_size") %>%
    pull(estimate)
}
hist(boot_coefs) #Now this looks somewhat decent

#Calculating the confidence interval from the bootstrap 
ci <- quantile(boot_coefs, c(0.025, 0.975))
cat("Bootstrap %95 CI", ci[[1]], "to", ci[[2]], "\n")
#Result -> Bootstrap %95 CI 1.565704 to 3.294318 

#Comparing classic parametric CI from the model which is based on a t statistic
cat("Parametric 95% CI", tidy(m, conf.int = TRUE) %>%
    filter(term == "Group_size") %>%
    pull(conf.low), "to", tidy(m, conf.int = TRUE) %>%
    filter(term == "Group_size") %>%
    pull(conf.high), "\n")
#Result -> Parametric 95% CI 1.769874 to 3.156269 


#Do these CIs suggest that your slope coefficient is different from zero?
##Both CIs being positive indicate a positive linear relationship between ECV and Group size
```
